### ISSUE TITLE
New placeholder request (UUID)

### ISSUE THREAD

**Issue by GoodLucky777** [Nukkit-coders/NPC#13]
I know there is placeholder called %p, but Luckyperm have a problem with nickname that have a space. So can you add a new placeholder called %u (UUID)? Luckperm work with UUID, too.

**Comment by PetteriM1** [comment]
Yes I can add that

**Comment by GoodLucky777** [comment]
Thanks!

**Comment by PetteriM1** [comment]
Added in version 2.3.0
