### ISSUE TITLE
!!! Please read (NPC Rotation)

### ISSUE THREAD

**Issue by ghost** [Nukkit-coders/NPC#16]
I want to delete my Cloudburst and Github Account, so I wanted to ask, if you'd like to host my NPC Rotation Plugin for this, so that it's not lost. (https://cloudburstmc.org/resources/npcrotation.413/)

**Comment by PetteriM1** [comment]
Okay. I will fork it to Nukkit Coders and update the link. Thanks for letting me know.

**Comment by ghost** [comment]
Thank you!
