### ISSUE TITLE
Problem Spawning Npc

### ISSUE THREAD

**Issue by Sinpul** [Nukkit-coders/NPC#2]
It always says entity not found, although I list them and do what's on the list

**Comment by PetteriM1** [comment]
You sure you wrote first letters upper case like Creeper or PolarBear?

**Comment by Sinpul** [comment]
No, I will re-install it. I didn't know it had to be exact. My bad

**Comment by Sinpul** [comment]
Update. it works. You should put that in the description lol. Btw great work on all the plugins

**Comment by Sinpul** [comment]
How do you add a command properly? It says
usage: /npc addcmd <ID> <Command>
I'm trying to use it for skyblock so I'm putting
/npc addcmd -+SkyBlock+- /skyblock
Is there something else I need to do?

**Comment by PetteriM1** [comment]
use `/npc addplayercmd <npc id> skyblock`
so id instead of npc name and no / to command
if you use addcmd instead of addplayercmd the command will run as console

**Comment by Sinpul** [comment]
Says the same thing still

**Comment by PetteriM1** [comment]
So what it says?

**Comment by Sinpul** [comment]
I typed
/npc addplayercmd §6-+SkyBlock+- skyblock
It says
usage: /npc addplayer cmd <ID> <cmd>

**Comment by PetteriM1** [comment]
You did it wrong. Npc id is not same as it's name. Use /npc get id and touch it to get it's id.

**Comment by Sinpul** [comment]
Ahh it worked. Thank You for Helping
