### ISSUE TITLE
ClearLag

### ISSUE THREAD

**Issue by timothytay** [Nukkit-coders/NPC#3]
When ClearLag occurs, all NPC’s disappear as well. Not sure if it’s the problem with ClearLag or this plugin though.

**Comment by PetteriM1** [comment]
ClearLag clears all entities (expect players) including npcs, holograms etc.

**Comment by PetteriM1** [comment]
If you download latest ClearLag it don't kill human entities (example human npcs)

**Comment by ghost** [comment]
@PetteriM1 waw, you can fix very well that.
