### ISSUE TITLE
/npc getid  and /npc remove don't work

### ISSUE THREAD

**Issue by Saxavlax001** [Nukkit-coders/NPC#4]
When I use that command and I'm trying to tap an npc,the plugin doesn't tell me the npc id.

**Comment by Saxavlax001** [comment]
@PetteriM1 sorry for tag,but this plugin is abandoned and I thought you wouldn't response.Pls fix it.

**Comment by Saxavlax001** [comment]
Also and /npc remove doesn't work.

**Comment by PetteriM1** [comment]
They work for me. Do you have other plugins that could cause this like MultiChat?

**Comment by Saxavlax001** [comment]
Yes whats the problem with multichat

**Comment by PetteriM1** [comment]
Disabling multichat nametag formatting should fix it

**Comment by Saxavlax001** [comment]
Ok works thank you.
