### ISSUE TITLE
Additional display about the NPCs

### ISSUE THREAD

**Issue by DueKay** [Nukkit-coders/NPC#8]
Is there a way for you to place another ad above the NPCs (and under the NPC name)?

I've connected my servers through Waterdog, and would be happy if I could see a total of 5/100 online affiliate NPCs (from lobby to servers)

best regards
DueKay

**Comment by PetteriM1** [comment]
Using score tag or what?

**Comment by DueKay** [comment]
Ich weiß nicht ob man das score tag nennt
Beispiel:
CityBuild (der Name des NPCs)
0/100 (spieleranzeige des verbundenen Servers)

Hoffe es ist so etwas verständlicher :)

Lg DueKay

--------------------------------------------------------

I do not know if you call the score tag
Example:
CityBuild (the name of the NPC)
0/100 (player display of the connected server)

Hope it is easier to understand :)

best regards
DueKay

**Comment by PetteriM1** [comment]
Added in version 2.3.0
