### ISSUE TITLE
Rotation.

### ISSUE THREAD

**Issue by MrReskill** [Nukkit-coders/NPC#9]
Is it possible to make npc rotate when player is around him (Like slapper rotation)..

If you don't want to do this, i will do it later. :)

See you ;).

**Comment by PetteriM1** [comment]
A bit late reply... There seems to be a plugin to add NPC rotation now
https://nukkitx.com/resources/npcrotation.413/

In my opinion it's good to have that as a separate plugin because of the performance impact it has and not everyone need this feature.

**Comment by MrReskill** [comment]
I saw his but I preferred to implement my own system in my Core being given that a party of this one also manages quite a lot concerning NPC via API (I put the plugin in dependency) ^ ^. But thanks :)
